service:
  name: hangman-cheater-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

functions:
  checkLetter:
    handler: functions/checkLetter/index.handler
    description: Gets the possible words given a dictionary and a hangman string (ex. do?ble where question mark is unresolved characters)
    events:
      - http:
          path: checkLetter
          method: post
  generateInitialWord:
    handler: functions/generateInitialWord/index.handler
    description: Chooses a random word from the dictionary
    events:
      - http:
          path: generateInitialWord
          method: post
plugins:
  - serverless-offline
